name: Deploy Strapi to ECS

on:
push:
branches:
- main
workflow_dispatch:

env:
AWS_REGION: ap-south-1
ECR_REPOSITORY: strapi-task7

jobs:
deploy:
runs-on: ubuntu-latest

steps:

  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  # 1️⃣ Create ECR if not exists
  - name: Create ECR Repository
    run: |
      aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
      aws ecr create-repository --repository-name $ECR_REPOSITORY

  # 2️⃣ Get ECR URI
  - name: Get ECR Repository URI
    id: repo-uri
    run: |
      REPO_URI=$(aws ecr describe-repositories \
        --repository-names $ECR_REPOSITORY \
        --query "repositories[0].repositoryUri" \
        --output text)
      echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV

  # 3️⃣ Login to ECR
  - name: Login to ECR
    uses: aws-actions/amazon-ecr-login@v2

  # 4️⃣ Generate image tag
  - name: Generate Image Tag
    run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  # 5️⃣ Build Image
  - name: Build Docker Image
    run: docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

  # 6️⃣ Tag Image
  - name: Tag Docker Image
    run: docker tag $ECR_REPOSITORY:$IMAGE_TAG $REPO_URI:$IMAGE_TAG

  # 7️⃣ Push Image
  - name: Push Docker Image
    run: docker push $REPO_URI:$IMAGE_TAG

  # 8️⃣ Setup Terraform
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init
    run: |
      cd terraform
      terraform init

  - name: Terraform Apply
    run: |
      cd terraform
      terraform apply -auto-approve \
        -var="image_tag=$IMAGE_TAG" \
        -var="ecr_repository_url=$REPO_URI"
